version: '3'

services:
  jellyfin-proxy:
    image: nginx:alpine
    container_name: jellyfin-proxy
    ports:
      - "${PROXY_PORT:-8080}:80"
    environment:
      - JELLYFIN_HOST=${JELLYFIN_HOST:-100.91.132.58}
      - JELLYFIN_PORT=${JELLYFIN_PORT:-8096}
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Starting nginx proxy for Jellyfin at $$JELLYFIN_HOST:$$JELLYFIN_PORT"
        
        cat > /etc/nginx/conf.d/default.conf <<EOF
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://$$JELLYFIN_HOST:$$JELLYFIN_PORT;
                proxy_set_header Host \$$host;
                proxy_set_header X-Real-IP \$$remote_addr;
                proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
                proxy_buffering off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$$http_upgrade;
                proxy_set_header Connection "upgrade";
            }
            
            location /health {
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }
        EOF
        
        echo "Config written. Contents:"
        cat /etc/nginx/conf.d/default.conf
        
        echo "Starting nginx..."
        exec nginx -g 'daemon off;'