version: '3'

services:
  jellyfin-proxy:
    image: nginx:alpine
    container_name: jellyfin-proxy
    ports:
      - "${PROXY_PORT:-8080}:80"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - JELLYFIN_HOST=${JELLYFIN_HOST:-100.91.132.58}
      - JELLYFIN_PORT=${JELLYFIN_PORT:-8096}
    restart: unless-stopped
    entrypoint: ["/bin/sh"]
    command: 
      - "-c"
      - |
        mkdir -p /etc/nginx/templates
        cat > /etc/nginx/templates/default.conf.template << 'EOF'
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://${JELLYFIN_HOST}:${JELLYFIN_PORT};
                proxy_set_header Host $$host;
                proxy_set_header X-Real-IP $$remote_addr;
                proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                proxy_buffering off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $$http_upgrade;
                proxy_set_header Connection "upgrade";
            }
            
            location /health {
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }
        EOF
        
        /docker-entrypoint.sh nginx -g 'daemon off;'