version: '3.8'

services:
  jellyfin-proxy:
    image: nginx:alpine
    container_name: jellyfin-proxy
    ports:
      - "${PROXY_PORT:-8080}:80"
    environment:
      - JELLYFIN_HOST=${JELLYFIN_HOST:-100.91.132.58}
      - JELLYFIN_PORT=${JELLYFIN_PORT:-8096}
    restart: unless-stopped
    command: >
      sh -c "
        cat > /etc/nginx/nginx.conf << 'EOF'
        events { 
            worker_connections 1024; 
        }

        http {
            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;
            types_hash_max_size 2048;

            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log;

            server {
                listen 80;
                server_name _;

                client_max_body_size 50M;

                location / {
                    proxy_pass http://${JELLYFIN_HOST}:${JELLYFIN_PORT};
      
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                    proxy_set_header X-Forwarded-Host \$server_name;
      
                    proxy_buffering off;
                    proxy_request_buffering off;
      
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection \$connection_upgrade;
      
                    proxy_connect_timeout 60s;
                    proxy_send_timeout 60s;
                    proxy_read_timeout 60s;
                }

                location /health {
                    access_log off;
                    return 200 'healthy';
                    add_header Content-Type text/plain;
                }
            }
      
            map \$http_upgrade \$connection_upgrade {
                default upgrade;
                '' close;
            }
        }
        EOF
      
        echo 'Starting nginx with config:'
        cat /etc/nginx/nginx.conf
        nginx -g 'daemon off;'
      "