version: '3'

services:
  jellyfin-proxy:
    image: nginx:alpine
    container_name: jellyfin-proxy
    ports:
      - "${PROXY_PORT:-8080}:80"
    restart: unless-stopped
    command: |
      sh -c '
        cat > /etc/nginx/conf.d/default.conf <<EOF
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://${JELLYFIN_HOST:-100.91.132.58}:${JELLYFIN_PORT:-8096};
                proxy_set_header Host \$$host;
                proxy_set_header X-Real-IP \$$remote_addr;
                proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$$scheme;
                
                proxy_buffering off;
                proxy_request_buffering off;
                
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$$http_upgrade;
                proxy_set_header Connection "upgrade";
                
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }
            
            location /health {
                return 200 "OK";
                add_header Content-Type text/plain;
            }
        }
        EOF
        
        rm -f /etc/nginx/conf.d/default.conf.bak
        nginx -g "daemon off;"
      '