version: '3.8'

services:
  jellyfin-proxy:
    image: nginx:alpine
    container_name: jellyfin-proxy
    ports:
      - "${PROXY_PORT:-8080}:80"
    environment:
      - JELLYFIN_HOST=${JELLYFIN_HOST:-100.91.132.58}
      - JELLYFIN_PORT=${JELLYFIN_PORT:-8096}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: |
      sh -c '
        cat > /etc/nginx/conf.d/default.conf << EOF
        server {
            listen 80;
            server_name _;

            client_max_body_size 50M;
            client_body_buffer_size 1M;

            location / {
                proxy_pass http://$$JELLYFIN_HOST:$$JELLYFIN_PORT;
                
                proxy_set_header Host \$$host;
                proxy_set_header X-Real-IP \$$remote_addr;
                proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$$scheme;
                proxy_set_header X-Forwarded-Host \$$server_name;
                
                proxy_buffering off;
                proxy_request_buffering off;
                
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$$http_upgrade;
                proxy_set_header Connection "upgrade";
                
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }

            location /health {
                access_log off;
                return 200 "healthy";
                add_header Content-Type text/plain;
            }
        }
        EOF
        
        echo "Nginx config generated. Starting nginx..."
        nginx -g "daemon off;"
      '